name: hiatunisie
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.5.1
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.4
  nb_utils: ^7.1.3
  socket_io_client: ^3.0.2
  flutter_local_notifications: ^19.0.0
  connectivity_plus: ^6.1.3

  http: ^1.0.0
  geocoding: ^3.0.0
  lottie: ^3.3.1
  provider: ^6.0.5
  map_location_picker: ^1.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  country_code_picker: ^3.0.0
  font_awesome_flutter: ^10.7.0
  vector_math: ^2.1.0
  flutter_map: ^8.1.1
  flutter_svg: ^2.0.17
  flutter_snake_navigationbar: ^0.6.1
  flutter_rating_bar: ^4.0.0
  readmore: ^3.0.0
  google_maps_flutter_web: ^0.5.8
  google_maps_flutter: ^2.1.3
  timeline_tile: ^2.0.0
  permission_handler: ^11.4.0
  dots_indicator: ^4.0.1
  shimmer: ^3.0.0
  gap: ^3.0.1
  device_preview: ^1.2.0
  intl: ^0.20.2
  url_launcher: ^6.0.12
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  icon_decoration: ^2.0.2
  fast_cached_network_image: ^1.2.9
  get: ^4.6.6
  latlong2: ^0.9.1
  screenshot: ^3.0.0
  shimmer_animation: ^2.2.1
  smooth_page_indicator: ^1.2.0+3
  google_places_flutter: ^2.0.6
  image_picker: ^1.1.2
  mime: ^2.0.0
  http_parser: ^4.1.2
  flutter_native_splash: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.1.2
  analyzer: ^6.4.1
  flutter_launcher_icons:

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/icon_hia.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "images/icon_hia.png"

flutter_native_splash:
  image: assets/logo_hia_splash_screen.png
  color: "#ffffff"
  android: true
  ios: true
  color_dark: "#000000"
  image_dark: assets/logo_hia_splash_screen.png
  icon_background_color: "#F7F8F9"



  android_12:
    icon_background_color: "#ffffff"
    android: true
    ios: true
    color_dark: "#000000"


flutter:
  uses-material-design: true

  assets:
  - images/
  - assets/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf

    - family: NeurialGroteskBoldT1
      fonts:
        - asset: assets/fonts/NeurialGrotesk/NeurialGrotesk-Extrabold.otf
          style: normal

    - family: NeurialGroteskBoldT2
      fonts:
        - asset: assets/fonts/NeurialGrotesk/NeurialGrotesk-Bold.otf
          style: normal

    - family: NeurialGroteskBolderMeduimT4
      fonts:
        - asset: assets/fonts/NeurialGrotesk/NeurialGrotesk-Medium.otf
          style: normal


    - family: NeurialGroteskBolderMeduimT4Italic
      fonts:
        - asset: assets/fonts/NeurialGrotesk/NeurialGrotesk-MediumItalic.otf
          style: italic
    - family: NeurialGroteskRegularRegularT8
      fonts:
        - asset: assets/fonts/NeurialGrotesk/NeurialGrotesk-Regular.otf
          style: normal